# Generated by Django 5.0.6 on 2024-07-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='reg_usernmae',
            new_name='reg_username',
        ),
    ]
