# Generated by Django 5.0.2 on 2024-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_category_alter_order_order_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.FileField(null=True, upload_to='category'),
        ),
    ]
