# Generated by Django 5.0.6 on 2024-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_catid',
            field=models.IntegerField(null=True),
        ),
    ]
