# Generated by Django 5.0.6 on 2024-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_con_text_contact_con_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=255)),
                ('reg_email', models.EmailField(max_length=255)),
                ('reg_number', models.CharField(max_length=20)),
                ('reg_usernmae', models.CharField(max_length=20)),
                ('reg_password', models.CharField(max_length=20)),
            ],
        ),
    ]
