# Generated by Django 5.0.7 on 2024-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_user', models.CharField(default=None, max_length=250)),
                ('order_name', models.CharField(max_length=250)),
                ('order_price', models.FloatField(max_length=250)),
                ('order_image', models.FloatField(null=True)),
                ('order_qty', models.IntegerField()),
                ('order_address', models.TextField(null=True)),
                ('order_dlptyp', models.CharField(max_length=10, null=True)),
                ('order_status', models.IntegerField(default=0)),
            ],
        ),
    ]
