# Generated by Django 5.0.7 on 2024-07-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.FloatField(null=True),
        ),
    ]
