# Generated by Django 5.0.2 on 2024-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_image', models.FileField(null=True, upload_to='product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
